on: push
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  add-blocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ruby
        uses: ruby/setup-ruby@v1

      - name: Add blocks
        run: ./bin/btc-blocks --output-path ./data/blocks --start-date $(date -d "1 day ago" -I -u)

      - name: Commit data
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "auto - "
          commit_message: "add block data"
